import axios from "axios";

const URL = "https://reactnative-expensetracker-default-rtdb.firebaseio.com/";

export const storeExpense = async (expenseData) => {
  const response = await axios.post(`${URL}/expenses.json`, expenseData);
  //id that was generated by firebase
  const id = response.data.name;
  return id;
};

export const fetchExpenses = async () => {
  //get returns promise.
  const response = await axios.get(`${URL}/expenses.json`);

  //get all data from firebase and structure it to an array of objects
  //firebase creates unique id for every data so use that id.
  const expenses = [];
  for (const key in response.data) {
    const expenseObj = {
      id: key,
      amount: response.data[key].amount,
      date: new Date(response.data[key].date),
      description: response.data[key].description,
    };
    expenses.push(expenseObj);
  }
  return expenses;
};

export const updateExpense = (id, expenseData) => {
  return axios.put(`${URL}/expenses/${id}.json`, expenseData);
};

export const deleteExpense = (id) => {
  return axios.delete(`${URL}/expenses/${id}.json`);
};
